micronaut:
  application:
    name: bank-transfer
  server:
    port: 8091

  jms:
    sqs:
      enabled: true

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT}

app:
  aws:
    sqs:
      bank-transfer-queue-name: bank-transfer

datasources:
  default:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driverClassName: ${database.driver:com.mysql.cj.jdbc.Driver}

flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    entity-scan:
      packages: 'com.blitzar.banktransfer.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
      show-sql: true

jackson:
  mapper:
    accept-case-insensitive-enums: true
    accept-single-value-as-array: true