// @no-log
POST {{host}}/api/v1/bank-transfers
Content-Type: application/json

{
  "accountFromIBAN": "ES6531908221216475895468",
  "transferValue": 1050.72,
  "accountToIBAN": "DE79500105177228677684",
  "reference": "Donate"
}